# Control configuration
engine:
  # The length of a cycle (in seconds)
  # cycle: 0.1

# Logging configuration
log:
  # Where log files go
  # dir: log/
  
  # Log system events (default: false)
  # events: true
  
  # Disables the log server (default: enabled)
  # server: false
  #
  # ... or configure it
  # server:
  #     # The port to listen on (for service discovery)
  #     port: 48933
  #     # The discovery period
  #     period: 10

  # Logging levels. It is a hash of component_name: level (where level is one
  # of DEBUG, INFO, WARN and FATAL). The output can be redirected in a file
  # using level:filename, in which case 'filename' is relative to the log
  # directory. Any occurence of 'ROBOT' in filename is replaced by the robot
  # name
  #
  # levels:
  #   roby: INFO
  #   roby/planning: DEBUG
  #   roby/distributed: DEBUG:ROBOT-distributed.log
  #   genom: INFO

# dRoby neighbour discovery
discovery:
  # The host:port at which we can connect to a discovery tuplespace
  # (default: no discovery tuplespace)
  # tuplespace: "localhost:29568"
  # The port at which we do ring discovery (default: disabled)
  # ring: 42865

# dRoby host configuration
droby:
  # How many errors are allowed before disconnecting from a peer
  # max_errors: 1
  # The ring discovery period if we do ring discovery
  # period: 0.5
  # The hostname at the dRoby server must listen to. It is either
  # 'host:port', or just ':port'
  # host: ":48902"

# Genom configuration
genom:
  # The memory size allocated for H2
  # mem_size: 4000000
  # If true, do not remove H2 devices when the application quit
  # keep_h2: false
  
# Pocosim configuration
pocosim:
  # The host of the GDHE display
  # display: localhost

  # An initialization script to display the scene on GDHE. The file is searched
  # in the data/ director
  # gdhe: lousa.gdhe
  
  # The Gazebo world file for pocosim/gazebo simulations. The file is searched
  # in the data/ directory 
  # gazebo: lousa.world

# Per-robot configuration. In these, you can override global options, or set
# new options.
# dala:
#   droby:
#     host: ":1287"

# vim: sw=2
